// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoInnovador.Data;

#nullable disable

namespace ProyectoInnovador.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520204122_AddArchivoOriginalDateCreatedUtc")]
    partial class AddArchivoOriginalDateCreatedUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("ProyectoInnovador.Models.ArchivoOriginal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Tamano")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("ArchivosOriginales");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.Fragmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchivoOriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashFragmento")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlRemota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoOriginalId");

                    b.ToTable("Fragmentos", t =>
                        {
                            t.HasCheckConstraint("CK_Fragmento_CloudProvider", "CloudProvider IN ('AWS','Azure')");
                        });
                });

            modelBuilder.Entity("ProyectoInnovador.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<bool>("EsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Free");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.ArchivoOriginal", b =>
                {
                    b.HasOne("ProyectoInnovador.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.Fragmento", b =>
                {
                    b.HasOne("ProyectoInnovador.Models.ArchivoOriginal", "ArchivoOriginal")
                        .WithMany("Fragmentos")
                        .HasForeignKey("ArchivoOriginalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivoOriginal");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.ArchivoOriginal", b =>
                {
                    b.Navigation("Fragmentos");
                });
#pragma warning restore 612, 618
        }
    }
}
