// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoInnovador.Data;

#nullable disable

namespace ProyectoInnovador.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513223709_AddSeedHashToArchivoOriginal")]
    partial class AddSeedHashToArchivoOriginal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("ProyectoInnovador.Models.ArchivoOriginal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Tamano")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ArchivosOriginales");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.Fragmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchivoOriginalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashFragmento")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlRemota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoOriginalId");

                    b.ToTable("Fragmentos", t =>
                        {
                            t.HasCheckConstraint("CK_Fragmento_CloudProvider", "CloudProvider IN ('AWS','Azure')");
                        });
                });

            modelBuilder.Entity("ProyectoInnovador.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.Fragmento", b =>
                {
                    b.HasOne("ProyectoInnovador.Models.ArchivoOriginal", "ArchivoOriginal")
                        .WithMany("Fragmentos")
                        .HasForeignKey("ArchivoOriginalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivoOriginal");
                });

            modelBuilder.Entity("ProyectoInnovador.Models.ArchivoOriginal", b =>
                {
                    b.Navigation("Fragmentos");
                });
#pragma warning restore 612, 618
        }
    }
}
